### ISSUE TITLE
archive.org/donate - part of form is not accessible

### ISSUE THREAD

**Issue by stemberajan** [polcak/jsrestrictor#153]
https://archive.org/donate

If I turn on JSR (state 1 or 2), I cannot fill the card info.

![image](https://user-images.githubusercontent.com/92169282/142590572-d8e83435-275b-4be8-8597-0d4ef3d829ec.png)

**Comment by polcak** [comment]
Steps to reproduce:

1. Open https://archive.org/donate
2. Choose a payment method: click on Credit card
3. I can fill in payment card details just above the Donate button in Firefox. But when I open in Edge, I cannot fill in the payment card details. I see many errors, see below.
4. I disabled JavaScript Shield, Network Boundary Shield, and Fingerprint Detector in Edge but the page is still broken in the same way.
5. I opened web dev tools and realized that that part of page is actually an iframe from https://assets.braintreegateway.com. Even if I disable JavaScript Shield through the options for assets.braintreegateway.com, I still cannot fill in payment details.
6. I disabled JShelter in the extension page, reloaded https://archive.org/donate and I can finally fill in  card details in Edge.

No other extensions installed in Edge.

The errors:

```
DOMException: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame.
    at <anonymous>:2242:25
    at <anonymous>:2276:4
    at <anonymous>:2280:4
    at <anonymous>:10600:4
    at anonymous (<anonymous>:10601:4)
    at modifyWindow (<anonymous>:199:7)
    at Object.patchWindow (<anonymous>:322:3)
    at <anonymous>:446:10
    at <anonymous>:10603:7
(anonymous) @ VM15:2276
(anonymous) @ VM15:2280
(anonymous) @ VM15:10600
anonymous @ VM15:10601
modifyWindow @ VM15:199
patchWindow @ VM15:322
(anonymous) @ VM15:446
(anonymous) @ VM15:10603
patchWindow @ patchWindow.js:201
configureInjection @ document_start.js:56
(anonymous) @ document_start.js:80
VM15:2441 
        
       DOMException: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame.
    at <anonymous>:2407:25
    at <anonymous>:2441:4
    at <anonymous>:2445:4
    at <anonymous>:10600:4
    at anonymous (<anonymous>:10601:4)
    at modifyWindow (<anonymous>:199:7)
    at Object.patchWindow (<anonymous>:322:3)
    at <anonymous>:446:10
    at <anonymous>:10603:7
(anonymous) @ VM15:2441
(anonymous) @ VM15:2445
(anonymous) @ VM15:10600
anonymous @ VM15:10601
modifyWindow @ VM15:199
patchWindow @ VM15:322
(anonymous) @ VM15:446
(anonymous) @ VM15:10603
patchWindow @ patchWindow.js:201
configureInjection @ document_start.js:56
(anonymous) @ document_start.js:80
VM15:2523 
...

       DOMException: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame.
    at <anonymous>:4906:25
    at <anonymous>:4940:4
    at <anonymous>:4944:4
    at <anonymous>:10600:4
    at anonymous (<anonymous>:10601:4)
    at modifyWindow (<anonymous>:199:7)
    at Object.patchWindow (<anonymous>:322:3)
    at <anonymous>:446:10
    at <anonymous>:10603:7
(anonymous) @ VM93:4940
(anonymous) @ VM93:4944
(anonymous) @ VM93:10600
anonymous @ VM93:10601
modifyWindow @ VM93:199
patchWindow @ VM93:322
(anonymous) @ VM93:446
(anonymous) @ VM93:10603
patchWindow @ patchWindow.js:201
configureInjection @ document_start.js:56
(anonymous) @ document_start.js:80
recaptcha__en.js:735 
        
       Uncaught DOMException: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame.
    at O2.E.De (https://www.gstatic.com/recaptcha/releases/QENb_qRrX0-mQMyENQjD6Fuj/recaptcha__en.js:735:52)
    at Array.<anonymous> (https://www.gstatic.com/recaptcha/releases/QENb_qRrX0-mQMyENQjD6Fuj/recaptcha__en.js:124:302)
    at Object.init (https://www.gstatic.com/recaptcha/releases/QENb_qRrX0-mQMyENQjD6Fuj/recaptcha__en.js:743:298)
    at https://www.google.com/recaptcha/api2/bframe?hl=en&v=QENb_qRrX0-mQMyENQjD6Fuj&k=6Ld64a8UAAAAAGbDwi1927ztGNw7YABQ-dqzvTN2:184:30
```

**Comment by polcak** [comment]
I opened a issue https://pagure.io/JShelter/webextension/issue/56
